#!/bin/bash -e

quaketestcommand="+timedemo demos/fps4"
quakedir="$HOME/games/quake"
gitdir="/home/git/ezquake-source-official"
optimizations="-march=native -O3 -pipe"
clangver="15"
profiledir="/tmp/ezquakeprofile"

if [ ! -e "$quakedir/id1/pak0.pak" ];then
	echo "pak files not found in quakedir.  bailing out."
	exit 1
fi

sudo apt -y install clang-$clangver llvm-$clangver lld-$clangver libclang-rt-$clangver-dev

cd "$gitdir"

rm -rf "$profiledir"
mkdir -p "$profiledir"


echo "CC=clang-$clangver
CFLAGS=$optimizations -fprofile-instr-generate=$profiledir/default.profraw
LDFLAGS=$optimizations -fuse-ld=lld-$clangver -fprofile-instr-generate=$profiledir/default.profraw" > "$profiledir/.config_1"

echo "CC=clang-$clangver
CFLAGS=$optimizations -flto -fprofile-use=$profiledir/default.profdata
LDFLAGS=$optimizations -flto -fuse-ld=lld-$clangver -fprofile-use=$profiledir/default.profdata" > "$profiledir/.config_2"

make clean
EZ_CONFIG_FILE="$profiledir/.config_1" make -j$(nproc)

./ezquake-linux-$(uname -m) -basedir $quakedir $quaketestcommand

make clean

llvm-profdata-$clangver merge $profiledir/*.profraw -o $profiledir/default.profdata

EZ_CONFIG_FILE="$profiledir/.config_2" make -j$(nproc)
