#!/bin/bash -e

quaketestscript="quake +timedemo demos/fps4"
gitdir="/home/git/ezquake-source-official"
optimizations="-march=native -O3 -fno-stack-protector -pipe"
clangver="15"
profiledir="/tmp/ezquakeprofile"

cd "$gitdir"

rm -rf "$profiledir"
mkdir -p "$profiledir"


echo "CC=clang-$clangver
CFLAGS=$optimizations -fprofile-instr-generate=$profiledir/default.profraw
LDFLAGS=$optimizations -fprofile-instr-generate=$profiledir/default.profraw" > "$profiledir/.config_1"

echo "CC=clang-$clangver
CFLAGS=$optimizations -fprofile-use=$profiledir/default.profdata -flto
LDFLAGS=$optimizations -fprofile-use=$profiledir/default.profdata -flto" > "$profiledir/.config_2"

make clean
EZ_CONFIG_FILE="$profiledir/.config_1" make -j$(nproc)

$quaketestscript

make clean

llvm-profdata-$clangver merge $profiledir/*.profraw -o $profiledir/default.profdata

EZ_CONFIG_FILE="$profiledir/.config_2" make -j$(nproc)
